### ISSUE TITLE
Feature Request: Allow to Play a Random Song on My Library While Muted.

### ISSUE THREAD

**Issue by tipar** [Xeroday/Spotify-Ad-Blocker#115] opened 2017-06-03 14:10 UTC
Hi. Thanks for the app. I was wondering if you could make possible to select a folder full of MP3 or other formats—not important—and play a randomly selected track while Spotify it is muted. You can even let the song finish or stop it when the audio ad it is finished as an option.

I would be happy if I could just simply select an audio file to play while muted because I am fearing that if you are listening to some Classical Music or sort of and the app randomly select an Atmospheric Black Metal track, the mix and the change in volume could be weird, unless you could introduce some kind of replay gain.

I think that that is all I wanted to say. Regards.

**Comment by Xeroday** [comment] 2017-07-30 00:18
Closing as it's a dupe of #14 .

**Closed by Xeroday** 2017-07-30 00:18 UTC
